version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - echo "🔧 Installing AWS CDK and dependencies..."
      - npm install -g aws-cdk
      - pip install -r requirements.txt

  build:
    commands:
      - echo "🚀 Running CDK Synth to generate CloudFormation template..."
      - cdk synth
      - ls -al cdk.out/  # Debugging step to confirm output exists
      - cp cdk.out/SimplePipelineStack.template.json .  # Move template to root

artifacts:
  files:
    - "SimplePipelineStack.template.json"  # Template must be at root level
    - "**/*"
  discard-paths: yes  # Ensures files are not nested
