version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - echo "🔧 Installing AWS CDK and dependencies..."
      - npm install -g aws-cdk
      - pip install -r requirements.txt

  build:
    commands:
      - echo "🚀 Running CDK synth to generate CloudFormation template..."
      - cdk synth
      - echo "📁 Listing contents of cdk.out directory for debugging..."
      - ls -al cdk.out/
      - echo "📂 Copying CloudFormation template to artifact root..."
      - cp cdk.out/SimplePipelineStack.template.json .

artifacts:
  files:
    - "SimplePipelineStack.template.json"
  discard-paths: yes
